# Save current values before refactoring
print("Recording current values before refactoring...")
print()
print("Expected Household Results:")
print("  Total CA households: 14.2M")
print("  Households with rebate: 3.3M (23%)")
print("  Average rebate base: $18,303")
print("  Total rebate base: $60.5B")
print()
print("Expected Tax Unit Results:")
print("  Total CA tax units: 21.3M")
print("  Tax units with rebate: 8.9M (42%)")
print("  Average rebate base: $16,455")
print("  Total rebate base: $146.5B")
