"""
Compare legacy webapp charts (old stack) vs current PolicyEngine output.

This script runs the same CTC/EITC reform on the CURRENT policyengine-us stack
with both datasets and produces side-by-side comparison charts against the
legacy payload (already generated by render_legacy_webapp_charts.py).

Run:
    uv run --python 3.11 \
      --with policyengine-us \
      --with plotly \
      python us/irs/income/credits/ctc/compare_legacy_vs_current.py

Prerequisites:
    The legacy payload must already exist at:
    us/irs/income/credits/ctc/legacy_webapp_charts/impact_payload.json
    (generated by render_legacy_webapp_charts.py using the old pinned stack)
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import plotly.graph_objects as go
from policyengine_us import Microsimulation
from policyengine_core.reforms import Reform


CPS_2023 = Path(
    "/Users/pavelmakarchuk/policyengine-us-data/policyengine_us_data/storage/cps_2023.h5"
)
ENHANCED_CPS_2024 = "enhanced_cps_2024"
LEGACY_PAYLOAD = Path(
    "us/irs/income/credits/ctc/legacy_webapp_charts/impact_payload.json"
)

BLUE = "#2C6496"
BLUE_LIGHT = "#D8E6F3"
DARK_GRAY = "#616161"
ORANGE = "#E8871E"
ORANGE_LIGHT = "#FCEBD6"
PLOT_FONT = "Roboto Serif"

YEAR = 2025

REFORM_DICT = {
    "gov.irs.credits.eitc.max[0].amount": {"2025-01-01.2100-12-31": 2000},
    "gov.irs.credits.eitc.max[1].amount": {"2025-01-01.2100-12-31": 2000},
    "gov.irs.credits.eitc.max[2].amount": {"2025-01-01.2100-12-31": 2000},
    "gov.irs.credits.eitc.max[3].amount": {"2025-01-01.2100-12-31": 2000},
    "gov.irs.credits.ctc.phase_out.amount": {"2025-01-01.2100-12-31": 25},
    "gov.irs.credits.ctc.amount.arpa[0].amount": {"2025-01-01.2100-12-31": 4800},
    "gov.irs.credits.ctc.amount.arpa[1].amount": {"2025-01-01.2100-12-31": 4800},
    "gov.irs.credits.ctc.phase_out.arpa.amount": {"2025-01-01.2100-12-31": 25},
    "gov.contrib.ctc.minimum_refundable.in_effect": {"2025-01-01.2100-12-31": True},
    "gov.contrib.ctc.per_child_phase_in.in_effect": {"2025-01-01.2100-12-31": True},
    "gov.irs.credits.ctc.phase_out.arpa.in_effect": {"2025-01-01.2100-12-31": True},
    "gov.irs.credits.ctc.refundable.phase_in.rate": {"2025-01-01.2100-12-31": 0.2},
    "gov.irs.credits.eitc.phase_in_rate[0].amount": {"2025-01-01.2100-12-31": 0.2},
    "gov.irs.credits.eitc.phase_in_rate[1].amount": {"2025-01-01.2100-12-31": 0.2},
    "gov.irs.credits.eitc.phase_in_rate[2].amount": {"2025-01-01.2100-12-31": 0.2},
    "gov.irs.credits.eitc.phase_in_rate[3].amount": {"2025-01-01.2100-12-31": 0.2},
    "gov.contrib.ctc.per_child_phase_out.in_effect": {"2025-01-01.2100-12-31": True},
    "gov.irs.credits.ctc.phase_out.threshold.JOINT": {"2025-01-01.2100-12-31": 200000},
    "gov.irs.credits.ctc.refundable.individual_max": {"2025-01-01.2100-12-31": 4800},
    "gov.irs.credits.eitc.phase_out.rate[0].amount": {"2025-01-01.2100-12-31": 0.1},
    "gov.irs.credits.eitc.phase_out.rate[1].amount": {"2025-01-01.2100-12-31": 0.1},
    "gov.irs.credits.eitc.phase_out.rate[2].amount": {"2025-01-01.2100-12-31": 0.1},
    "gov.irs.credits.eitc.phase_out.rate[3].amount": {"2025-01-01.2100-12-31": 0.1},
    "gov.irs.credits.ctc.phase_out.threshold.SINGLE": {"2025-01-01.2100-12-31": 100000},
    "gov.irs.credits.eitc.phase_out.start[0].amount": {"2025-01-01.2100-12-31": 20000},
    "gov.irs.credits.eitc.phase_out.start[1].amount": {"2025-01-01.2100-12-31": 20000},
    "gov.irs.credits.eitc.phase_out.start[2].amount": {"2025-01-01.2100-12-31": 20000},
    "gov.irs.credits.eitc.phase_out.start[3].amount": {"2025-01-01.2100-12-31": 20000},
    "gov.irs.credits.ctc.phase_out.threshold.SEPARATE": {"2025-01-01.2100-12-31": 100000},
    "gov.contrib.ctc.per_child_phase_out.avoid_overlap": {"2025-01-01.2100-12-31": True},
    "gov.irs.credits.ctc.refundable.phase_in.threshold": {"2025-01-01.2100-12-31": 0},
    "gov.irs.credits.ctc.phase_out.arpa.threshold.JOINT": {"2025-01-01.2100-12-31": 35000},
    "gov.contrib.ctc.minimum_refundable.amount[0].amount": {"2025-01-01.2100-12-31": 2400},
    "gov.contrib.ctc.minimum_refundable.amount[1].amount": {"2025-01-01.2100-12-31": 2400},
    "gov.irs.credits.ctc.phase_out.arpa.threshold.SINGLE": {"2025-01-01.2100-12-31": 25000},
    "gov.irs.credits.eitc.phase_out.joint_bonus[0].amount": {"2025-01-01.2100-12-31": 7000},
    "gov.irs.credits.eitc.phase_out.joint_bonus[1].amount": {"2025-01-01.2100-12-31": 7000},
    "gov.irs.credits.ctc.phase_out.arpa.threshold.SEPARATE": {"2025-01-01.2100-12-31": 25000},
    "gov.irs.credits.ctc.phase_out.threshold.SURVIVING_SPOUSE": {"2025-01-01.2100-12-31": 100000},
    "gov.irs.credits.ctc.phase_out.threshold.HEAD_OF_HOUSEHOLD": {"2025-01-01.2100-12-31": 100000},
    "gov.irs.credits.ctc.phase_out.arpa.threshold.SURVIVING_SPOUSE": {"2025-01-01.2100-12-31": 25000},
    "gov.irs.credits.ctc.phase_out.arpa.threshold.HEAD_OF_HOUSEHOLD": {"2025-01-01.2100-12-31": 25000},
}


def build_reform() -> Reform:
    return Reform.from_dict(REFORM_DICT, country_id="us")


def compute_budget(baseline: Microsimulation, reformed: Microsimulation, year: int) -> dict:
    """Compute budgetary impact matching the API/app-v2 approach.

    Uses household_tax and household_benefits at household level.
    MicroSeries.sum() auto-applies household_weight.
    """
    # household_tax includes fed+state+local taxes minus refundable credits
    b_tax = baseline.calculate("household_tax", period=year).sum()
    r_tax = reformed.calculate("household_tax", period=year).sum()
    b_state_tax = baseline.calculate("state_income_tax", period=year).sum()
    r_state_tax = reformed.calculate("state_income_tax", period=year).sum()

    b_benefits = baseline.calculate("household_benefits", period=year).sum()
    r_benefits = reformed.calculate("household_benefits", period=year).sum()

    tax_revenue_impact = float(r_tax - b_tax)
    state_tax_revenue_impact = float(r_state_tax - b_state_tax)
    benefit_spending_impact = float(r_benefits - b_benefits)
    budgetary_impact = tax_revenue_impact - benefit_spending_impact

    return {
        "tax_revenue_impact": tax_revenue_impact,
        "state_tax_revenue_impact": state_tax_revenue_impact,
        "benefit_spending_impact": benefit_spending_impact,
        "budgetary_impact": budgetary_impact,
    }


def compute_decile_impacts(
    baseline: Microsimulation, reformed: Microsimulation, year: int
) -> dict:
    """Compute average and relative income change by decile.

    Matches the API: uses pre-computed household_income_decile (person-weighted)
    and household_weight for aggregation.
    """
    import pandas as pd

    b_income = baseline.calculate("household_net_income", period=year)
    r_income = reformed.calculate("household_net_income", period=year)
    hh_weight = baseline.calculate("household_weight", period=year)
    # Pre-computed decile variable uses person-weighted ranking
    decile = baseline.calculate("household_income_decile", period=year)

    df = pd.DataFrame({
        "baseline": b_income.values,
        "reform": r_income.values,
        "weight": hh_weight.values,
        "decile": decile.values,
    })
    df["change"] = df["reform"] - df["baseline"]

    average = {}
    relative = {}
    for d in range(1, 11):
        mask = df["decile"] == d
        sub = df[mask]
        w = sub["weight"]
        total_change = (sub["change"] * w).sum()
        total_baseline = (sub["baseline"] * w).sum()
        total_weight = w.sum()
        average[str(d)] = float(total_change / total_weight) if total_weight > 0 else 0.0
        relative[str(d)] = float(total_change / total_baseline) if total_baseline != 0 else 0.0

    return {"average": average, "relative": relative}


def compute_poverty(
    baseline: Microsimulation, reformed: Microsimulation, year: int
) -> dict:
    """Compute poverty rate changes matching the API/app-v2.

    Uses person_in_poverty (person-level variable derived from spm_unit)
    weighted by person_weight. Poverty rate = weighted mean.
    """
    import pandas as pd

    # person_in_poverty is the person-level variable (maps spm_unit in_poverty to persons)
    b_poverty = baseline.calculate("person_in_poverty", period=year)
    r_poverty = reformed.calculate("person_in_poverty", period=year)
    person_weight = baseline.calculate("person_weight", period=year)
    age = baseline.calculate("age", period=year)

    df = pd.DataFrame({
        "b_poverty": b_poverty.values,
        "r_poverty": r_poverty.values,
        "weight": person_weight.values,
        "age": age.values,
    })

    def poverty_rates(mask):
        sub = df[mask] if mask is not None else df
        w = sub["weight"]
        b_rate = (sub["b_poverty"] * w).sum() / w.sum()
        r_rate = (sub["r_poverty"] * w).sum() / w.sum()
        return {"baseline": float(b_rate), "reform": float(r_rate)}

    return {
        "child": poverty_rates(df["age"] < 18),
        "adult": poverty_rates((df["age"] >= 18) & (df["age"] < 65)),
        "senior": poverty_rates(df["age"] >= 65),
        "all": poverty_rates(None),
    }


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--cps-2023", default=str(CPS_2023))
    parser.add_argument("--enhanced-cps-2024", default=ENHANCED_CPS_2024)
    parser.add_argument("--legacy-payload", default=str(LEGACY_PAYLOAD))
    parser.add_argument("--year", type=int, default=YEAR)
    parser.add_argument(
        "--output-dir",
        default="us/irs/income/credits/ctc/legacy_webapp_charts",
    )
    return parser.parse_args()


def write_chart(fig: go.Figure, path: Path) -> None:
    fig.write_html(str(path), include_plotlyjs="cdn")
    print(f"  Wrote: {path}")


def render_budget_comparison(legacy: dict, current_cps: dict, current_ecps: dict, outdir: Path) -> None:
    """Side-by-side budgetary impact."""
    datasets = ["Legacy (old stack, CPS 23)", "Current (CPS 23)", "Current (ECPS 24)"]
    budgets = [legacy["budget"], current_cps, current_ecps]

    fig = go.Figure()
    for i, (label, budget) in enumerate(zip(datasets, budgets)):
        net = budget["budgetary_impact"] / 1e9
        fig.add_trace(go.Bar(
            x=[label],
            y=[net],
            name=label,
            marker_color=[BLUE, DARK_GRAY, ORANGE][i],
            text=[f"${net:,.1f}bn"],
            textposition="outside",
        ))

    fig.update_layout(
        title="Net Budgetary Impact: Legacy vs Current Stack",
        yaxis={"title": "Net budgetary impact ($bn)", "tickformat": "$,.1f"},
        font={"family": PLOT_FONT},
        plot_bgcolor="rgba(0,0,0,0)",
        showlegend=False,
        height=500,
        margin={"t": 60, "b": 80, "l": 80, "r": 20},
    )
    write_chart(fig, outdir / "comparison_budget.html")


def render_decile_comparison(legacy: dict, current_cps: dict, current_ecps: dict, outdir: Path) -> None:
    """Decile average impact comparison."""
    legacy_avg = legacy["decile"]["average"]
    deciles = list(legacy_avg.keys())

    fig = go.Figure()
    fig.add_trace(go.Bar(
        x=deciles,
        y=list(legacy_avg.values()),
        name="Legacy (old stack, CPS 23)",
        marker_color=BLUE,
    ))
    fig.add_trace(go.Bar(
        x=deciles,
        y=[current_cps["average"].get(d, 0) for d in deciles],
        name="Current (CPS 23)",
        marker_color=DARK_GRAY,
    ))
    fig.add_trace(go.Bar(
        x=deciles,
        y=[current_ecps["average"].get(d, 0) for d in deciles],
        name="Current (ECPS 24)",
        marker_color=ORANGE,
    ))

    fig.update_layout(
        title="Average Income Change by Decile: Legacy vs Current",
        xaxis={"title": "Income decile"},
        yaxis={"title": "Average change ($)", "tickformat": "$,.0f"},
        barmode="group",
        font={"family": PLOT_FONT},
        plot_bgcolor="rgba(0,0,0,0)",
        height=550,
        margin={"t": 60, "b": 80, "l": 80, "r": 20},
        legend={"yanchor": "top", "y": 0.99, "xanchor": "right", "x": 0.99},
    )
    write_chart(fig, outdir / "comparison_decile_average.html")


def render_poverty_comparison(legacy: dict, current_cps: dict, current_ecps: dict, outdir: Path) -> None:
    """Poverty rate change comparison."""
    categories = ["child", "adult", "senior", "all"]
    labels = ["Children", "Working-age", "Seniors", "All"]

    legacy_pov = legacy["poverty"]["poverty"]

    def get_changes(pov_data):
        return [pov_data[k]["reform"] / pov_data[k]["baseline"] - 1 for k in categories]

    fig = go.Figure()
    fig.add_trace(go.Bar(
        x=labels,
        y=get_changes(legacy_pov),
        name="Legacy (old stack, CPS 23)",
        marker_color=BLUE,
    ))
    fig.add_trace(go.Bar(
        x=labels,
        y=get_changes(current_cps),
        name="Current (CPS 23)",
        marker_color=DARK_GRAY,
    ))
    fig.add_trace(go.Bar(
        x=labels,
        y=get_changes(current_ecps),
        name="Current (ECPS 24)",
        marker_color=ORANGE,
    ))

    fig.update_layout(
        title="Poverty Rate Change: Legacy vs Current",
        xaxis={"title": ""},
        yaxis={"title": "Relative change in poverty rate", "tickformat": "+,.1%"},
        barmode="group",
        font={"family": PLOT_FONT},
        plot_bgcolor="rgba(0,0,0,0)",
        height=500,
        margin={"t": 60, "b": 80, "l": 80, "r": 20},
        legend={"yanchor": "top", "y": 0.99, "xanchor": "right", "x": 0.99},
    )
    write_chart(fig, outdir / "comparison_poverty.html")


def main() -> None:
    args = parse_args()
    outdir = Path(args.output_dir)
    outdir.mkdir(parents=True, exist_ok=True)

    # Load legacy payload
    legacy_path = Path(args.legacy_payload)
    if not legacy_path.exists():
        print(f"WARNING: Legacy payload not found at {legacy_path}")
        print("Run render_legacy_webapp_charts.py first with the old pinned stack.")
        print("Proceeding with current-stack-only comparison.\n")
        legacy = None
    else:
        legacy = json.loads(legacy_path.read_text())
        print(f"Loaded legacy payload from: {legacy_path}")

    reform = build_reform()

    # Run current stack with CPS 2023
    print(f"\nRunning current stack with CPS 2023...")
    baseline_cps = Microsimulation(dataset=args.cps_2023)
    reformed_cps = Microsimulation(dataset=args.cps_2023, reform=reform)
    budget_cps = compute_budget(baseline_cps, reformed_cps, args.year)
    decile_cps = compute_decile_impacts(baseline_cps, reformed_cps, args.year)
    poverty_cps = compute_poverty(baseline_cps, reformed_cps, args.year)

    # Run current stack with Enhanced CPS 2024
    print(f"Running current stack with Enhanced CPS 2024...")
    baseline_ecps = Microsimulation(dataset=args.enhanced_cps_2024)
    reformed_ecps = Microsimulation(dataset=args.enhanced_cps_2024, reform=reform)
    budget_ecps = compute_budget(baseline_ecps, reformed_ecps, args.year)
    decile_ecps = compute_decile_impacts(baseline_ecps, reformed_ecps, args.year)
    poverty_ecps = compute_poverty(baseline_ecps, reformed_ecps, args.year)

    # Print summary table
    print("\n" + "=" * 80)
    print("BUDGETARY IMPACT COMPARISON")
    print("=" * 80)
    rows = [
        ("Legacy (old stack, CPS 23)", legacy["budget"] if legacy else None),
        ("Current (CPS 23)", budget_cps),
        ("Current (ECPS 24)", budget_ecps),
    ]
    print(f"{'Dataset':<30} {'Net impact ($bn)':>18} {'Tax rev ($bn)':>15} {'Benefits ($bn)':>15}")
    print("-" * 80)
    for label, b in rows:
        if b is None:
            print(f"{label:<30} {'N/A':>18} {'N/A':>15} {'N/A':>15}")
        else:
            print(
                f"{label:<30} "
                f"{b['budgetary_impact']/1e9:>18,.2f} "
                f"{b['tax_revenue_impact']/1e9:>15,.2f} "
                f"{b['benefit_spending_impact']/1e9:>15,.2f}"
            )

    # Save current-stack results
    current_results = {
        "cps_2023": {
            "budget": budget_cps,
            "decile": decile_cps,
            "poverty": poverty_cps,
        },
        "enhanced_cps_2024": {
            "budget": budget_ecps,
            "decile": decile_ecps,
            "poverty": poverty_ecps,
        },
    }
    results_path = outdir / "current_stack_results.json"
    results_path.write_text(json.dumps(current_results, indent=2))
    print(f"\nCurrent stack results saved to: {results_path}")

    # Render comparison charts
    if legacy:
        print("\nRendering comparison charts...")
        render_budget_comparison(legacy, budget_cps, budget_ecps, outdir)
        render_decile_comparison(legacy, decile_cps, decile_ecps, outdir)
        render_poverty_comparison(legacy, poverty_cps, poverty_ecps, outdir)

        # Also render an index page for the comparison
        comparison_index = outdir / "comparison_index.html"
        comparison_index.write_text(f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <title>Legacy vs Current Comparison</title>
    <style>
        body {{ margin: 0; font-family: "Roboto Serif", Georgia, serif; background: #f7fafd; }}
        main {{ max-width: 1200px; margin: 0 auto; padding: 32px 20px 60px; }}
        h1 {{ margin: 0 0 12px; font-size: 2rem; }}
        .intro {{ margin: 0 0 28px; padding: 16px 18px; background: white;
                  border-left: 4px solid #2C6496; box-shadow: 0 8px 24px rgba(12,26,39,0.06); }}
        section {{ margin: 0 0 28px; padding: 16px; background: white;
                   box-shadow: 0 8px 24px rgba(12,26,39,0.06); }}
        iframe {{ width: 100%; height: 620px; border: 1px solid #bdbdbd; background: white; }}
        h2 {{ margin: 0 0 12px; font-size: 1.15rem; }}
    </style>
</head>
<body>
<main>
    <h1>Legacy vs Current Stack Comparison</h1>
    <p class="intro">
        Comparing the same CTC/EITC reform across three configurations:<br>
        <strong>Legacy</strong> = old stack (policyengine 0.3.9 + policyengine-us 1.425.4 + CPS 2023)<br>
        <strong>Current CPS 23</strong> = current policyengine-us + CPS 2023<br>
        <strong>Current ECPS 24</strong> = current policyengine-us + Enhanced CPS 2024
    </p>
    <section>
        <h2>Net Budgetary Impact</h2>
        <iframe src="comparison_budget.html"></iframe>
    </section>
    <section>
        <h2>Distributional Impact (Average by Decile)</h2>
        <iframe src="comparison_decile_average.html"></iframe>
    </section>
    <section>
        <h2>Poverty Rate Change</h2>
        <iframe src="comparison_poverty.html"></iframe>
    </section>
</main>
</body>
</html>
""")
        print(f"  Wrote: {comparison_index}")
    else:
        print("\nSkipping comparison charts (no legacy payload available).")

    print("\nDone.")


if __name__ == "__main__":
    main()
